import { useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { borderRadius, type ThemeDefinition } from '../theme';
import { adminFontSize, adminSpacing, adminTouchTarget } from '../theme/admin';

const labels = ['일', '월', '화', '수', '목', '금', '토'];
const key = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;
const fromKey = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(Number(value.slice(0, 4)), Number(value.slice(5, 7)) - 1, Number(value.slice(8, 10))) : new Date();

export function DatePicker({ value, onChange, disabled, theme }: { readonly value: string; readonly onChange: (value: string) => void; readonly disabled?: boolean; readonly theme: ThemeDefinition }) {
  const [open, setOpen] = useState(false);
  const [month, setMonth] = useState(() => fromKey(value));
  const year = month.getFullYear(); const monthIndex = month.getMonth(); const first = new Date(year, monthIndex, 1).getDay(); const count = new Date(year, monthIndex + 1, 0).getDate();
  const choose = (day: number) => { onChange(key(new Date(year, monthIndex, day))); setOpen(false); };
  const move = (offset: number) => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + offset, 1));
  return <><Pressable accessibilityRole="button" accessibilityLabel="특정 날짜 고르기" disabled={disabled} onPress={() => { setMonth(fromKey(value)); setOpen(true); }} style={[styles.field, { borderColor: theme.colors.primary }]}><Text style={{ color: value ? theme.colors.text : theme.colors.textMuted }}>{value || '특정 날짜 고르기'}</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={[styles.dialog, { backgroundColor: theme.colors.surface }]}><View style={styles.header}><Pressable accessibilityRole="button" onPress={() => move(-1)} style={styles.nav}><Text style={{ color: theme.colors.primary }}>‹</Text></Pressable><Text style={[styles.title, { color: theme.colors.text }]}>{year}년 {monthIndex + 1}월</Text><Pressable accessibilityRole="button" onPress={() => move(1)} style={styles.nav}><Text style={{ color: theme.colors.primary }}>›</Text></Pressable></View><View style={styles.grid}>{labels.map((label) => <Text key={label} style={[styles.dayLabel, { color: theme.colors.textMuted }]}>{label}</Text>)}{Array.from({ length: first }, (_, index) => <View key={`empty-${index}`} style={styles.day} />)}{Array.from({ length: count }, (_, index) => { const day = index + 1; const selected = value === key(new Date(year, monthIndex, day)); return <Pressable key={day} accessibilityRole="button" onPress={() => choose(day)} style={[styles.day, selected && { backgroundColor: theme.colors.primary }]}><Text style={{ color: selected ? theme.colors.onPrimary : theme.colors.text }}>{day}</Text></Pressable>; })}</View><Pressable accessibilityRole="button" onPress={() => setOpen(false)} style={[styles.close, { backgroundColor: theme.colors.primary }]}><Text style={{ color: theme.colors.onPrimary }}>닫기</Text></Pressable></View></View></Modal></>;
}

const styles = StyleSheet.create({ field: { borderWidth: 1, borderRadius: borderRadius.sm, justifyContent: 'center', minHeight: adminTouchTarget, paddingHorizontal: adminSpacing.xs }, overlay: { alignItems: 'center', backgroundColor: '#00000088', flex: 1, justifyContent: 'center', padding: adminSpacing.md }, dialog: { borderRadius: borderRadius.lg, gap: adminSpacing.sm, maxWidth: 420, padding: adminSpacing.md, width: '100%' }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, title: { fontSize: adminFontSize.title, fontWeight: '700' }, nav: { alignItems: 'center', justifyContent: 'center', minHeight: adminTouchTarget, minWidth: adminTouchTarget }, grid: { flexDirection: 'row', flexWrap: 'wrap' }, dayLabel: { textAlign: 'center', width: '14.2857%' }, day: { alignItems: 'center', borderRadius: borderRadius.sm, height: adminTouchTarget, justifyContent: 'center', width: '14.2857%' }, close: { alignItems: 'center', borderRadius: borderRadius.sm, justifyContent: 'center', minHeight: adminTouchTarget } });
