import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { AppState, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { getPinLockUntil, hasPin, recordPinFailure, resetPinFailures, savePin, verifyPin } from '../security/pin';
import { borderRadius, type ThemeDefinition } from '../theme';
import { adminFontSize, adminSpacing, adminTouchTarget } from '../theme/admin';

export function PinGate({ children, theme }: { readonly children: ReactNode; readonly theme: ThemeDefinition }) {
  const [configured, setConfigured] = useState<boolean | null>(null); const [unlocked, setUnlocked] = useState(false); const [saving, setSaving] = useState(false); const [pin, setPin] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState('PIN을 확인하는 중이에요.'); const [lockedUntil, setLockedUntil] = useState(0); const [locked, setLocked] = useState(false);
  const session = useRef(0);
  const stateVersion = useRef(0);
  const saveInFlight = useRef<Promise<void> | null>(null);
  const failedAttempts = useRef(0);
  const loadPinState = useCallback(async () => { await saveInFlight.current?.catch(() => undefined); const loadVersion = ++stateVersion.current; setConfigured(null); setUnlocked(false); setPin(''); setConfirm(''); try { const value = await hasPin(); const until = await getPinLockUntil(); setLocked(Boolean(until)); setLockedUntil(until); if (loadVersion !== stateVersion.current) return; setConfigured(value); setMessage(value ? '편집 PIN을 입력해 주세요.' : '처음 사용할 PIN을 숫자 4~8자리로 정해 주세요.'); } catch { if (loadVersion === stateVersion.current) setMessage('PIN 저장소를 읽지 못했어요. 다시 시도해 주세요.'); } }, []);
  useEffect(() => { void Promise.resolve().then(loadPinState); const subscription = AppState.addEventListener('change', (state) => { if (state !== 'active') { session.current += 1; stateVersion.current += 1; setUnlocked(false); setPin(''); setConfirm(''); } else void loadPinState(); }); return () => subscription.remove(); }, [loadPinState]);
  useEffect(() => { if (!lockedUntil) return; const timer = setTimeout(() => { setLockedUntil(0); setLocked(false); failedAttempts.current = 0; setMessage('PIN을 다시 입력해 주세요.'); }, Math.max(0, lockedUntil - Date.now())); return () => clearTimeout(timer); }, [lockedUntil]);
  const submit = async () => { if (configured === null || saving || saveInFlight.current || locked) return; const currentSession = session.current; const writeVersion = ++stateVersion.current; setSaving(true); try { if (configured === false) { if (pin !== confirm) throw new Error('PIN 확인이 같지 않아요.'); const write = savePin(pin); saveInFlight.current = write; await write; saveInFlight.current = null; if (writeVersion !== stateVersion.current) { void loadPinState(); return; } setConfigured(true); if (currentSession !== session.current) return; setUnlocked(true); setMessage('PIN을 저장하고 편집을 열었어요.'); } else if (await verifyPin(pin)) { failedAttempts.current = 0; await resetPinFailures(); if (writeVersion !== stateVersion.current || currentSession !== session.current) return; setUnlocked(true); setMessage('편집을 열었어요.'); } else { failedAttempts.current += 1; const until = await recordPinFailure(); if (until) { setLocked(true); setLockedUntil(until); setMessage('PIN을 여러 번 틀려 5분 동안 잠갔어요.'); } else setMessage('PIN이 맞지 않아요.'); } } catch (error) { saveInFlight.current = null; if (writeVersion === stateVersion.current) setMessage(error instanceof Error ? error.message : 'PIN을 확인하지 못했어요.'); } finally { setSaving(false); } };
  if (unlocked) return <>{children}</>;
  const loading = configured === null;

  return <View style={[styles.card, { backgroundColor: theme.decorations.cardBackground, borderColor: theme.decorations.cardBorder }]}><Text accessibilityRole="header" style={[styles.heading, { color: theme.colors.text }]}>편집 PIN</Text><TextInput accessibilityLabel="PIN" editable={!loading && !saving && !locked} secureTextEntry keyboardType="number-pad" maxLength={8} value={pin} onChangeText={setPin} placeholder="숫자 4~8자리" style={styles.input} />{configured === false && <TextInput accessibilityLabel="PIN 확인" editable={!saving && !locked} secureTextEntry keyboardType="number-pad" maxLength={8} value={confirm} onChangeText={setConfirm} placeholder="PIN 다시 입력" style={styles.input} />}{loading ? <Pressable accessibilityRole="button" onPress={() => void loadPinState()} style={[styles.button, { backgroundColor: theme.colors.primary }]}><Text style={{ color: theme.colors.onPrimary }}>다시 확인</Text></Pressable> : <Pressable accessibilityRole="button" disabled={saving || locked} onPress={() => void submit()} style={[styles.button, { backgroundColor: theme.colors.primary }]}><Text style={{ color: theme.colors.onPrimary }}>{saving ? '저장 중' : locked ? '잠김' : configured ? '편집 열기' : 'PIN 저장하고 편집 열기'}</Text></Pressable>}<Text accessibilityLiveRegion="polite" style={{ color: theme.colors.textMuted }}>{message}</Text></View>;
}

const styles = StyleSheet.create({ card: { borderRadius: borderRadius.lg, borderWidth: 2, gap: adminSpacing.xs, padding: adminSpacing.md, width: '100%' }, heading: { fontSize: adminFontSize.title, fontWeight: '700' }, input: { borderColor: '#64748B', borderRadius: borderRadius.sm, borderWidth: 1, fontSize: adminFontSize.body, minHeight: adminTouchTarget, paddingHorizontal: adminSpacing.xs }, button: { alignItems: 'center', borderRadius: borderRadius.md, justifyContent: 'center', minHeight: adminTouchTarget } });
