-- TimeTable 서버: 보석 자격 테이블 추가와 로컬 데이터 최초 이전 함수 (백로그 P6.5)
--
-- 1) tt_gem_rights: 로컬 gem_rights(스키마 V12, P4.13 '5일 연속 달성 → 실물 보석 자격')에 대응한다.
--    P6.2 서버 스키마(로컬 버전 11 기준) 뒤에 생긴 테이블이라 빠져 있었다.
-- 2) tt_import_local(p_family, p_payload): 딸 폰 앱이 로컬 SQLite 행을 그대로 보내면 한 트랜잭션으로 서버에 넣는다.
--    - security invoker라 호출한 계정의 권한과 보안 규칙(RLS)이 그대로 적용된다(가족 구성원만 자기 가족에 넣을 수 있다).
--    - 서버가 새 id를 붙이고, 함수 안에서 로컬 id → 서버 id를 짝지어 세트·할 일 참조를 유지한다
--      (로컬 id를 그대로 넣으면 id 시퀀스를 맞춰야 하는데 앱 계정에는 그 권한이 없다).
--    - 가족에 이미 시간표·할 일 등 데이터가 있으면 아무것도 넣지 않고 멈춘다(두 번 올려 중복되는 것을 막는다).
--    - 로컬 시각은 SQLite CURRENT_TIMESTAMP(UTC, 'YYYY-MM-DD HH:MM:SS'), 반복 요일은 '1,3,5' 문자열이라 여기서 변환한다.
--    - 로컬의 'local-child'는 그 가족의 딸(child) 계정으로 바꾼다.

-- ---------------------------------------------------------------------------
-- 보석 자격
-- ---------------------------------------------------------------------------

create table public.tt_gem_rights (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  child_id uuid not null,
  earned_date date not null,
  state text not null default 'available' check (state in ('available', 'requested', 'given')),
  requested_at timestamptz,
  given_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, child_id, earned_date),
  -- 보석 원장과 같이 구성원을 뺄 때 이력이 조용히 사라지지 않게 cascade를 쓰지 않는다
  foreign key (family_id, child_id) references public.tt_family_members (family_id, user_id)
);
-- (family_id, child_id) 외래키는 위 unique 인덱스의 앞부분이 덮으므로 따로 인덱스를 두지 않는다
create index tt_gem_rights_state_idx on public.tt_gem_rights (family_id, state);

create trigger tt_gem_rights_touch_updated_at before update on public.tt_gem_rights
  for each row execute function tt_private.touch_updated_at();

alter table public.tt_gem_rights enable row level security;
create policy tt_gem_rights_family_members on public.tt_gem_rights
  for all to authenticated
  using ((select tt_private.is_family_member(family_id)))
  with check ((select tt_private.is_family_member(family_id)));

grant select, insert, update, delete on public.tt_gem_rights to authenticated, service_role;
grant usage, select on sequence public.tt_gem_rights_id_seq to authenticated, service_role;
revoke all on public.tt_gem_rights from anon;
revoke all on sequence public.tt_gem_rights_id_seq from anon;
revoke truncate, references, trigger on public.tt_gem_rights from authenticated;

-- ---------------------------------------------------------------------------
-- 로컬 데이터 최초 이전
-- ---------------------------------------------------------------------------

-- SQLite UTC 문자열(또는 ISO 문자열)을 timestamptz로. 비어 있으면 null
create function tt_private.import_ts(p text) returns timestamptz
language sql stable
set search_path = ''
as $$ select case when p is null or btrim(p) = '' then null else (p::timestamp at time zone 'UTC') end $$;

create function public.tt_import_local(p_family uuid, p_payload jsonb) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_child uuid;
  r jsonb;
  v_id bigint;
  v_sets jsonb := '{}'::jsonb;
  v_tasks jsonb := '{}'::jsonb;
  v_counts jsonb := '{}'::jsonb;
  n integer;
begin
  if p_family is null or p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'TT_IMPORT: 잘못된 요청입니다';
  end if;
  -- 구성원이 아니면(RLS로 자기 가족만 보임) 딸 계정을 찾지 못해 멈춘다
  select m.user_id into v_child from public.tt_family_members m
    where m.family_id = p_family and m.role = 'child' order by m.created_at limit 1;
  if v_child is null then raise exception 'TT_IMPORT: 이 가족의 딸 계정을 찾지 못했습니다'; end if;
  if exists (select 1 from public.tt_periods where family_id = p_family)
     or exists (select 1 from public.tt_timetable_sets where family_id = p_family)
     or exists (select 1 from public.tt_tasks where family_id = p_family)
     or exists (select 1 from public.tt_sticker_ledger where family_id = p_family)
     or exists (select 1 from public.tt_rewards where family_id = p_family)
     or exists (select 1 from public.tt_day_exceptions where family_id = p_family)
     or exists (select 1 from public.tt_gem_rights where family_id = p_family) then
    raise exception 'TT_IMPORT: 서버에 이미 이 가족의 데이터가 있습니다';
  end if;

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'periods', '[]'::jsonb)) loop
    insert into public.tt_periods (family_id, period_no, start_time, end_time, created_at)
      values (p_family, (r ->> 'period_no')::integer, r ->> 'start_time', r ->> 'end_time', coalesce(tt_private.import_ts(r ->> 'created_at'), now()));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('periods', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'timetable_sets', '[]'::jsonb)) loop
    insert into public.tt_timetable_sets (family_id, name, created_at)
      values (p_family, r ->> 'name', coalesce(tt_private.import_ts(r ->> 'created_at'), now()))
      returning id into v_id;
    v_sets := v_sets || jsonb_build_object(r ->> 'id', v_id);
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('timetable_sets', n);

  r := p_payload -> 'timetable_settings';
  if r is not null and jsonb_typeof(r) = 'object' then
    insert into public.tt_timetable_settings (family_id, active_set_id)
      values (p_family, (v_sets ->> (r ->> 'active_set_id'))::bigint);
    v_counts := v_counts || jsonb_build_object('timetable_settings', 1);
  end if;

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'timetable_items', '[]'::jsonb)) loop
    if v_sets ->> (r ->> 'set_id') is null then raise exception 'TT_IMPORT: 세트가 없는 시간표 항목이 있습니다'; end if;
    insert into public.tt_timetable_items (family_id, set_id, weekday, period_no, start_time, end_time, title, category,
        color_key, icon_key, alert_mode, alert_before_min, memo, created_at)
      values (p_family, (v_sets ->> (r ->> 'set_id'))::bigint, (r ->> 'weekday')::smallint, (r ->> 'period_no')::integer,
        r ->> 'start_time', r ->> 'end_time', r ->> 'title', r ->> 'category', r ->> 'color_key', r ->> 'icon_key',
        coalesce(r ->> 'alert_mode', 'none'), coalesce((r ->> 'alert_before_min')::integer, 0), coalesce(r ->> 'memo', ''),
        coalesce(tt_private.import_ts(r ->> 'created_at'), now()));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('timetable_items', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'day_exceptions', '[]'::jsonb)) loop
    insert into public.tt_day_exceptions (family_id, start_date, end_date, type, note)
      values (p_family, (r ->> 'start_date')::date, (r ->> 'end_date')::date, r ->> 'type', coalesce(r ->> 'note', ''));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('day_exceptions', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'tasks', '[]'::jsonb)) loop
    insert into public.tt_tasks (family_id, title, repeat_weekdays, task_date, remind_time, alert_mode, sticker_reward,
        effective_from, effective_until, created_at)
      values (p_family, r ->> 'title',
        case when nullif(btrim(r ->> 'repeat_weekdays'), '') is null then null
             else string_to_array(btrim(r ->> 'repeat_weekdays'), ',')::smallint[] end,
        (r ->> 'task_date')::date, nullif(r ->> 'remind_time', ''), coalesce(r ->> 'alert_mode', 'none'),
        (r ->> 'sticker_reward')::integer, (r ->> 'effective_from')::date, (r ->> 'effective_until')::date,
        coalesce(tt_private.import_ts(r ->> 'created_at'), now()))
      returning id into v_id;
    v_tasks := v_tasks || jsonb_build_object(r ->> 'id', v_id);
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('tasks', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'task_completions', '[]'::jsonb)) loop
    if v_tasks ->> (r ->> 'task_id') is null then raise exception 'TT_IMPORT: 할 일이 없는 완료 기록이 있습니다'; end if;
    insert into public.tt_task_completions (family_id, task_id, completion_date, done_at, done_by)
      values (p_family, (v_tasks ->> (r ->> 'task_id'))::bigint, (r ->> 'completion_date')::date,
        coalesce(tt_private.import_ts(r ->> 'done_at'), now()), coalesce(r ->> 'done_by', 'child'));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('task_completions', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'task_completion_history', '[]'::jsonb)) loop
    if v_tasks ->> (r ->> 'task_id') is null then raise exception 'TT_IMPORT: 할 일이 없는 완료 이력이 있습니다'; end if;
    insert into public.tt_task_completion_history (family_id, task_id, completion_date)
      values (p_family, (v_tasks ->> (r ->> 'task_id'))::bigint, (r ->> 'completion_date')::date);
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('task_completion_history', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'sticker_ledger', '[]'::jsonb)) loop
    -- 지워진 할 일을 가리키던 행은 로컬처럼 task_id를 비운다
    insert into public.tt_sticker_ledger (family_id, child_id, delta, reason, task_id, created_at)
      values (p_family, v_child, (r ->> 'delta')::integer, r ->> 'reason', (v_tasks ->> (r ->> 'task_id'))::bigint,
        coalesce(tt_private.import_ts(r ->> 'created_at'), now()));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('sticker_ledger', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'rewards', '[]'::jsonb)) loop
    insert into public.tt_rewards (family_id, title, sticker_goal, achieved_at)
      values (p_family, r ->> 'title', (r ->> 'sticker_goal')::integer, tt_private.import_ts(r ->> 'achieved_at'));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('rewards', n);

  n := 0;
  for r in select * from jsonb_array_elements(coalesce(p_payload -> 'gem_rights', '[]'::jsonb)) loop
    insert into public.tt_gem_rights (family_id, child_id, earned_date, state, requested_at, given_at, created_at)
      values (p_family, v_child, (r ->> 'earned_date')::date, coalesce(r ->> 'state', 'available'),
        tt_private.import_ts(r ->> 'requested_at'), tt_private.import_ts(r ->> 'given_at'),
        coalesce(tt_private.import_ts(r ->> 'created_at'), now()));
    n := n + 1;
  end loop;
  v_counts := v_counts || jsonb_build_object('gem_rights', n);

  return v_counts;
end;
$$;

-- 로그인한 구성원만 부를 수 있다(함수 기본 PUBLIC 실행 권한을 회수)
revoke execute on function public.tt_import_local(uuid, jsonb) from public, anon;
grant execute on function public.tt_import_local(uuid, jsonb) to authenticated;
revoke execute on function tt_private.import_ts(text) from public, anon;
grant execute on function tt_private.import_ts(text) to authenticated;
