-- TimeTable 서버 스키마 (백로그 P6.2)
--
-- 설계 원칙
--  * 같은 Supabase 프로젝트에 Doro 테이블과 섞여도 겹치지 않게 모든 테이블 이름에 tt_ 접두사를 붙인다.
--  * 앱 로컬 SQLite(src/db/migrations.ts, 버전 11)와 같은 모양을 유지해 동기화(P6.6)에서 변환을 최소화한다.
--    - 날짜는 date(문자열 'YYYY-MM-DD'로 주고받는다), 시각은 로컬과 같은 'HH:MM' 문자열(text)로 둔다.
--    - tasks.repeat_weekdays는 로컬의 CSV 문자열 대신 smallint[]로 둔다(동기화에서 변환).
--  * 기본키는 bigint identity지만 "generated by default"라서, 최초 이전(P6.5) 때 로컬 id를 그대로 넣을 수 있다.
--    id를 직접 넣어 이전한 뒤에는 시퀀스를 맞춰야 한다(supabase/README.md 참고).
--  * 가족 소속을 검사하는 보안 규칙(RLS)은 다음 파일(…_tt_rls.sql)에서 만든다.
--  * 모든 외래키 열에는 인덱스를 둔다(삭제 연쇄와 조인이 느려지지 않게).

create schema if not exists tt_private;
grant usage on schema tt_private to authenticated;

-- ---------------------------------------------------------------------------
-- 가족과 구성원
-- ---------------------------------------------------------------------------

create table public.tt_families (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) > 0),
  created_at timestamptz not null default now()
);

create table public.tt_family_members (
  family_id uuid not null references public.tt_families (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('parent', 'child')),
  display_name text not null default '',
  created_at timestamptz not null default now(),
  primary key (family_id, user_id),
  -- 한 계정은 한 가족에만 속한다(보안 규칙의 소속 조회를 단순하게 유지)
  unique (user_id)
);

-- ---------------------------------------------------------------------------
-- 시간표
-- ---------------------------------------------------------------------------

create table public.tt_periods (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  period_no integer not null check (period_no > 0),
  start_time text not null check (start_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  end_time text not null check (end_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, period_no)
);

create table public.tt_timetable_sets (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  name text not null check (char_length(btrim(name)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, name),
  -- 다른 테이블이 (family_id, id)로 참조해 "같은 가족의 세트"만 가리키게 한다
  unique (family_id, id)
);

-- 가족마다 한 줄: 지금 적용 중인 시간표 세트
create table public.tt_timetable_settings (
  family_id uuid primary key references public.tt_families (id) on delete cascade,
  active_set_id bigint,
  updated_at timestamptz not null default now(),
  foreign key (family_id, active_set_id) references public.tt_timetable_sets (family_id, id) on delete set null (active_set_id)
);
create index tt_timetable_settings_active_set_idx on public.tt_timetable_settings (family_id, active_set_id);

create table public.tt_timetable_items (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  set_id bigint not null,
  weekday smallint not null check (weekday between 0 and 6),
  period_no integer,
  start_time text check (start_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  end_time text check (end_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  title text not null check (char_length(btrim(title)) > 0),
  category text not null check (category in ('school', 'academy', 'care', 'life')),
  color_key text not null check (color_key in ('korean', 'math', 'english', 'science', 'music', 'art', 'physical-education', 'academy', 'life', 'other')),
  icon_key text not null check (icon_key in ('text', 'number', 'alphabet', 'experiment', 'music-note', 'art-tool', 'activity', 'academy', 'life', 'other')),
  alert_mode text not null default 'none' check (alert_mode in ('none', 'notify', 'alarm')),
  alert_before_min integer not null default 0 check (alert_before_min >= 0),
  -- 앱의 MAX_MEMO_LENGTH(100)와 같다. char_length는 글자(코드포인트) 수를 센다
  memo text not null default '' check (char_length(memo) <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (family_id, set_id) references public.tt_timetable_sets (family_id, id) on delete cascade,
  foreign key (family_id, period_no) references public.tt_periods (family_id, period_no),
  -- 교시로 정하거나(period_no) 시작·끝 시각으로 정한다(둘 중 하나만)
  check ((period_no is not null and start_time is null and end_time is null)
      or (period_no is null and start_time is not null and end_time is not null))
);
create index tt_timetable_items_set_weekday_idx on public.tt_timetable_items (family_id, set_id, weekday);
create index tt_timetable_items_period_idx on public.tt_timetable_items (family_id, period_no);

create table public.tt_day_exceptions (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  start_date date not null,
  end_date date not null,
  type text not null check (type in ('holiday', 'vacation', 'discretionary')),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);
create index tt_day_exceptions_dates_idx on public.tt_day_exceptions (family_id, start_date, end_date);

-- ---------------------------------------------------------------------------
-- 할 일과 완료 기록
-- ---------------------------------------------------------------------------

create table public.tt_tasks (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  title text not null check (char_length(btrim(title)) > 0),
  -- 요일 반복(0=일 … 6=토). 특정 날짜 할 일이면 null
  repeat_weekdays smallint[] check (
    repeat_weekdays is null
    or (cardinality(repeat_weekdays) > 0 and repeat_weekdays <@ array[0, 1, 2, 3, 4, 5, 6]::smallint[])
  ),
  task_date date,
  remind_time text check (remind_time is null or remind_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  alert_mode text not null default 'none' check (alert_mode in ('none', 'notify', 'alarm')),
  sticker_reward integer,
  -- 반복 할 일이 적용되는 기간(종료일 다음 날부터는 목록·계산·알림에서 빠진다)
  effective_from date,
  effective_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (repeat_weekdays is not null or task_date is not null),
  check (effective_from is null or effective_until is null or effective_until >= effective_from),
  unique (family_id, id)
);
create index tt_tasks_family_date_idx on public.tt_tasks (family_id, task_date);

-- 날짜별 완료 기록(취소하면 지워진다). family_id는 보안 규칙을 빠르게 하려고 함께 둔다
create table public.tt_task_completions (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  task_id bigint not null,
  completion_date date not null,
  done_at timestamptz not null default now(),
  done_by text not null default 'child' check (done_by in ('child', 'parent')),
  unique (task_id, completion_date),
  foreign key (family_id, task_id) references public.tt_tasks (family_id, id) on delete cascade
);
create index tt_task_completions_task_idx on public.tt_task_completions (family_id, task_id);
create index tt_task_completions_date_idx on public.tt_task_completions (family_id, completion_date);

-- 한 번이라도 완료한 적이 있는 날짜(취소해도 남는다). 이력이 있는 반복 할 일은 지우지 않고 종료일로 그만둔다
create table public.tt_task_completion_history (
  family_id uuid not null references public.tt_families (id) on delete cascade,
  task_id bigint not null,
  completion_date date not null,
  primary key (task_id, completion_date),
  foreign key (family_id, task_id) references public.tt_tasks (family_id, id) on delete cascade
);
create index tt_task_completion_history_task_idx on public.tt_task_completion_history (family_id, task_id);

-- ---------------------------------------------------------------------------
-- 보석(스티커) 원장과 보상 목표
-- ---------------------------------------------------------------------------

create table public.tt_sticker_ledger (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  child_id uuid not null,
  delta integer not null,
  reason text not null,
  task_id bigint,
  created_at timestamptz not null default now(),
  -- 구성원을 빼거나 계정을 지울 때 보석 이력이 조용히 사라지지 않게 cascade를 쓰지 않는다(기본 no action).
  -- 가족 전체를 지울 때는 원장도 같은 문장에서 함께 지워지므로 막히지 않는다.
  foreign key (family_id, child_id) references public.tt_family_members (family_id, user_id),
  foreign key (family_id, task_id) references public.tt_tasks (family_id, id) on delete set null (task_id)
);
create index tt_sticker_ledger_family_idx on public.tt_sticker_ledger (family_id, created_at);
create index tt_sticker_ledger_child_idx on public.tt_sticker_ledger (family_id, child_id);
create index tt_sticker_ledger_task_idx on public.tt_sticker_ledger (family_id, task_id);
-- 하루 전체 완료와 보석 보상은 같은 이유로 두 번 적립되지 않는다(로컬 앱과 같은 규칙)
create unique index tt_sticker_ledger_completion_reason_idx on public.tt_sticker_ledger (family_id, reason)
  where reason like 'daily-completion:%' or reason like 'gem-reward:%';

create table public.tt_rewards (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.tt_families (id) on delete cascade,
  title text not null check (char_length(btrim(title)) > 0),
  sticker_goal integer not null check (sticker_goal > 0),
  achieved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index tt_rewards_family_idx on public.tt_rewards (family_id);

-- ---------------------------------------------------------------------------
-- 기기와 동기화 상태 (푸시 토큰, 마지막 동기화 시각)
-- ---------------------------------------------------------------------------

create table public.tt_devices (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.tt_families (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  push_token text,
  platform text not null default 'android',
  last_synced_at timestamptz,
  scheduled_count integer check (scheduled_count is null or scheduled_count >= 0),
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- 한 설치본에서 로그인 계정을 바꿔도 같은 토큰을 새 계정 이름으로 다시 등록할 수 있게 (계정, 토큰) 단위로 유일하게 한다
  unique (user_id, push_token)
);
create index tt_devices_family_idx on public.tt_devices (family_id);
create index tt_devices_user_idx on public.tt_devices (user_id);

-- ---------------------------------------------------------------------------
-- updated_at 자동 갱신: 서버가 행을 바꾼 시각을 기록한다(클라이언트가 보낸 값은 무시하고 서버 시각으로 덮어쓴다).
-- 행을 지우는 경우는 알 수 없으므로(삭제 기록이 없다) 변경 감지에는 쓸 수 있지만 삭제 전파에는 쓸 수 없다. supabase/README.md 참고
-- ---------------------------------------------------------------------------

create function tt_private.touch_updated_at() returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array[
    'tt_periods', 'tt_timetable_sets', 'tt_timetable_settings', 'tt_timetable_items',
    'tt_day_exceptions', 'tt_tasks', 'tt_rewards', 'tt_devices'
  ] loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function tt_private.touch_updated_at()',
      t || '_touch_updated_at', t
    );
  end loop;
end;
$$;
