/** @jest-environment node */
import { MAX_MEMO_LENGTH } from '../src/db/timetableRepository';
import { timetableCategories } from '../src/db/types';
import { colorKeys, iconKeys } from '../src/theme';

// 서버 스키마(supabase/migrations)가 앱 코드와 어긋나지 않는지 정적으로 검사한다.
// 실제 Postgres에 적용해 보는 검증은 아니므로, 적용 결과는 Supabase에서 따로 확인해야 한다.
/* eslint-disable @typescript-eslint/no-require-imports */
// @types/node를 추가하지 않고(라이브러리 정책) Node 내장 모듈을 require로 불러온다. jest는 프로젝트 루트에서 실행된다
const { readFileSync, readdirSync } = require('node:fs') as { readFileSync(path: string, encoding: 'utf8'): string; readdirSync(path: string): string[] };
/* eslint-enable @typescript-eslint/no-require-imports */

const directory = 'supabase/migrations';
const files = readdirSync(directory).filter((name: string) => name.endsWith('.sql')).sort();
const read = (suffix: string) => readFileSync(`${directory}/${files.find((name: string) => name.endsWith(suffix)) ?? ''}`, 'utf8');
const schema = read('_tt_schema.sql');
const rls = read('_tt_rls.sql');

const createdTables = [...schema.matchAll(/create table public\.(tt_\w+)/g)].map((match) => match[1]);
const quoted = (values: readonly string[]) => values.map((value) => `'${value}'`).join(', ');

describe('supabase 마이그레이션', () => {
  it('파일 이름이 시간순으로 스키마 다음에 보안 규칙이 적용되게 정렬된다', () => {
    expect(files.map((name: string) => name.replace(/^\d+_/, ''))).toEqual(['tt_schema.sql', 'tt_rls.sql']);
  });

  it('모든 테이블 이름에 tt_ 접두사가 붙어 Doro 테이블과 겹치지 않는다', () => {
    expect(createdTables.length).toBeGreaterThanOrEqual(13);
    for (const match of schema.matchAll(/create table (?:if not exists )?(?:public\.)?(\w+)/g)) expect(match[1]).toMatch(/^tt_/);
  });

  it('만든 모든 테이블에 보안 규칙(RLS)을 켜고 anon 권한을 회수한다', () => {
    const enabledDirectly = [...rls.matchAll(/alter table public\.(tt_\w+) enable row level security/g)].map((match) => match[1]);
    const loopLists = [...rls.matchAll(/foreach t in array array\[([^\]]*)\]/g)].map((match) => [...match[1].matchAll(/'(tt_\w+)'/g)].map((item) => item[1]));
    const enabledInLoop = loopLists[0] ?? [];
    const revokedInLoop = loopLists[1] ?? [];
    for (const table of createdTables) {
      expect([...enabledDirectly, ...enabledInLoop]).toContain(table);
      expect(revokedInLoop).toContain(table);
    }
  });

  it('보안 규칙에 쓰는 소속 확인 함수는 로그인한 사용자에게만 실행 권한을 준다', () => {
    for (const fn of ['tt_private.is_family_member(uuid)', 'tt_private.is_family_parent(uuid)', 'public.tt_create_family(text, text)']) {
      expect(rls).toContain(`revoke execute on function ${fn} from public, anon;`);
      expect(rls).toContain(`grant execute on function ${fn} to authenticated;`);
    }
    expect((rls.match(/^security definer$/gm) ?? []).length).toBe(3);
    expect((rls.match(/^set search_path = ''$/gm) ?? []).length).toBe(3);
  });

  it('정책 안의 auth.uid()는 select로 감싸 한 번만 계산한다', () => {
    for (const match of rls.matchAll(/auth\.uid\(\)/g)) expect(rls.slice(Math.max(0, (match.index ?? 0) - 8), match.index)).toBe('(select ');
  });

  it('메모 최대 길이와 종류·색·아이콘 목록이 앱 코드와 같다', () => {
    expect(schema).toContain(`char_length(memo) <= ${MAX_MEMO_LENGTH}`);
    expect(schema).toContain(`category in (${quoted(timetableCategories)})`);
    expect(schema).toContain(`color_key in (${quoted(colorKeys)})`);
    expect(schema).toContain(`icon_key in (${quoted(iconKeys)})`);
  });

  it('로컬 id를 그대로 이전할 수 있게 identity가 generated by default다', () => {
    expect(schema).not.toContain('generated always');
    expect(schema).toContain('generated by default as identity');
  });

  it('외래키가 있는 테이블마다 가족 기준 인덱스가 있다', () => {
    for (const table of createdTables.filter((name: string) => name !== 'tt_families' && name !== 'tt_family_members')) {
      const hasIndex = new RegExp(`create (?:unique )?index \\w+ on public\\.${table} \\(family_id`).test(schema)
        || new RegExp(`create table public\\.${table} \\([^;]*(?:unique \\(family_id|family_id uuid primary key)`).test(schema);
      expect({ table, hasIndex }).toEqual({ table, hasIndex: true });
    }
  });
});
